// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/BlogPosts.tsx";
import * as $$$$$$1 from "./sections/CardsCarousel.tsx";
import * as $$$$$$2 from "./sections/CardsTrio.tsx";
import * as $$$$$$3 from "./sections/Faq.tsx";
import * as $$$$$$4 from "./sections/Footer.tsx";
import * as $$$$$$5 from "./sections/FooterLP.tsx";
import * as $$$$$$6 from "./sections/Header.tsx";
import * as $$$$$$7 from "./sections/HeaderHero.tsx";
import * as $$$$$$18 from "./sections/hero-1.tsx";
import * as $$$$$$19 from "./sections/hero-2.tsx";
import * as $$$$$$8 from "./sections/Hero.tsx";
import * as $$$$$$20 from "./sections/hero2.tsx";
import * as $$$$$$9 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$10 from "./sections/LiveSales.tsx";
import * as $$$$$$11 from "./sections/Logos.tsx";
import * as $$$$$$12 from "./sections/Partnering.tsx";
import * as $$$$$$13 from "./sections/RealTour.tsx";
import * as $$$$$$14 from "./sections/StockManagement.tsx";
import * as $$$$$$15 from "./sections/Testimonials.tsx";
import * as $$$$$$16 from "./sections/Theme/Theme.tsx";
import * as $$$$$$17 from "./sections/WorldMap.tsx";

const manifest = {
  "sections": {
    "site/sections/BlogPosts.tsx": $$$$$$0,
    "site/sections/CardsCarousel.tsx": $$$$$$1,
    "site/sections/CardsTrio.tsx": $$$$$$2,
    "site/sections/Faq.tsx": $$$$$$3,
    "site/sections/Footer.tsx": $$$$$$4,
    "site/sections/FooterLP.tsx": $$$$$$5,
    "site/sections/Header.tsx": $$$$$$6,
    "site/sections/HeaderHero.tsx": $$$$$$7,
    "site/sections/hero-1.tsx": $$$$$$18,
    "site/sections/hero-2.tsx": $$$$$$19,
    "site/sections/Hero.tsx": $$$$$$8,
    "site/sections/hero2.tsx": $$$$$$20,
    "site/sections/ImageWithParagraph.tsx": $$$$$$9,
    "site/sections/LiveSales.tsx": $$$$$$10,
    "site/sections/Logos.tsx": $$$$$$11,
    "site/sections/Partnering.tsx": $$$$$$12,
    "site/sections/RealTour.tsx": $$$$$$13,
    "site/sections/StockManagement.tsx": $$$$$$14,
    "site/sections/Testimonials.tsx": $$$$$$15,
    "site/sections/Theme/Theme.tsx": $$$$$$16,
    "site/sections/WorldMap.tsx": $$$$$$17,
  },
  "apps": {
    "site/apps/decohub.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
